config/routes.rb
Rails.application.routes.draw do

  devise_for :models
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  
  root to: 'stories#index'
  
  resources :stories do 
    resources :comments
    resources :bookmarks
    resources :pictures, only: [:destroy, :new, :create]
  end
  
  namespace :admin do
    root to: 'stories#index'
    resources :stories
  end
  
  resources :dashboard, except: [:index] do
    member do
      get 'authored_stories'
      get 'bookmarked_stories'
      get 'commented_stories'
      get 'followers'
      get 'followings'
      get 'notifications'
    end
    devise_for :users, controllers: { registrations: 'registrations' }
  end
  
  resources :reactions, only: [:create, :destroy]
  
  resources :followings, only: [:show, :create, :destroy]
  
  resources :registration_steps, only: [:show, :update]

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_user, only: [:show, :authored_stories, :bookmarked_stories, :commented_stories, :followings, :followers, :notifications]
  
  before_action :set_authored_stories, only: [:show, :authored_stories]  
  before_action :set_posted_stories, only: [:show, :authored_stories]  
  before_action :set_bookmarked_stories, only: [:show, :bookmarked_stories]
  before_action :set_commented_stories, only: [:show, :commented_stories]
  before_action :set_followers, only: [:show, :followers]
  before_action :set_followings, only: [:show, :followings]
  before_action :set_notifications, only: [:show, :notifications]
  
  def show
  end
  
  def authored_stories
    respond_to do |format|
      format.js {render :partial => 'dashboard/authored_stories'} 
    end
  end
  
  def bookmarked_stories
    respond_to do |format|
      format.js {render :partial => 'dashboard/bookmarked_stories'} 
    end
  end
  
  def commented_stories
    respond_to do |format|
      format.js {render :partial => 'dashboard/commented_stories'} 
    end
  end
  
  def followers
    respond_to do |format|
      format.js {render :partial => 'dashboard/followers'} 
    end
  end
  
  def followings
    respond_to do |format|
      format.js {render :partial => 'dashboard/followings'} 
    end
  end
  
  def notifications
    respond_to do |format|
      format.js {render :partial => 'dashboard/notifications'} 
    end
  end
  
  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def set_authored_stories
    @authored_stories = Story.where(author_id: @user)
  end
  
  def set_posted_stories
    @posted_stories = Story.where(poster_id: @user)
  end
  
  def set_notifications
    @notifications = Notification.where(user_id: @user.id)
    @unread_notifications = Notification.where(user_id: @user.id, read: false)
  end
  
#  def set_liked_stories
#    if @user == current_user
#      @liked_stories = Story.where.not(author_id: @user.id).joins(:story_likes).where(:story_likes => { :user_id => @user.id})
#    else
#      @liked_stories = Story.joins(:story_likes).where(:story_likes => { :user_id => @user.id})
#    end
#  end
  
  def set_bookmarked_stories
    @bookmarked_stories = Story.where.not(author_id: @user.id).joins(:bookmarks).where(:bookmarks => { :user_id => @user.id})
  end
  
  def set_commented_stories
    @commented_stories = Story.joins(:comments).where(:comments => { :user_id => @user.id})
  end
  
  def set_followers
    @followers = Following.where(user_id: @user.id)
  end
  
  def set_followings
    @followings = Following.where(follower_id: @user.id)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def user_photo(user)
    if @user.image_file_name?
      image_tag @user.image.url(:medium)
    elsif @user.fbimage?
      image_tag(@user.largesquareimage)
    else
      if @user == current_user
        link_to "Upload Photo", edit_user_dashboard_registration_path(@user), remote: true
      end
    end
  end
  
  def story_main_image(story)
    unless story.main_image_file_name.nil?
      image_tag story.main_image.url
    end
  end
  
  def story_title(story)
    if story.published?
      if story.last_user_to_update == "Admin"
        body = story.final_title
      else
        body = story.updated_title
      end
    else
      body = story.raw_title
    end
  end
  
  def story_body(story)
    if story.published?
      if story.last_user_to_update == "Admin"
        body = story.final_body
      else
        body = story.updated_body
      end
    else
      body = story.raw_body
    end
    if body.nil?
      body = "PROBLEM"
    else
      truncate_body_list(body)
    end
  end
  
  def story_pending(story)
    unless story.published?
      html = "<div>Pending</div>".html_safe
    end
  end
  
  def story_anonymous(story)
    if story.anonymous?
      html = "<div>Anonymous</div>".html_safe
    end
  end
  
  def story_by(story)
    if story.poster_id?
      html = "<div>Posted by: #{User.find(story.poster_id).full_name}</div>".html_safe
    else
      html = "<div>Written by: #{User.find(story.author_id).full_name}</div>".html_safe
    end
  end
end

app/views/dashboard/_authored_stories.js.erb
$("#dashboard_partial").html("<%= j render partial: 'authored_stories.html.slim' %>");

app/views/dashboard/_bookmarked_stories.html.slim
h2 List of All Saved Stories:
- @bookmarked_stories.each do |story|
  div
    == story_main_image(story)
  div
    == link_to story_title(story), story_path(story)
  div
    == story_body(story)
  div
    small 
      | Posted by: 
      == link_to "#{User.find(story.poster_id).full_name}", dashboard_path(User.find(story.poster_id))
  div
    small
      | Posted on: 
      == story.created_at.strftime("%b %d, %Y")

app/views/dashboard/_bookmarked_stories.js.erb
$("#dashboard_partial").html("<%= j render partial: 'bookmarked_stories.html.slim' %>");

app/views/dashboard/_commented_stories.html.slim
h2 List of All Commented Stories:
- @commented_stories.each do |story|
  div
    == story_main_image(story)
  div
    == link_to story_title(story), story_path(story)
  div
    == story_body(story)
  div
    small 
      | Posted by: 
      == link_to "#{User.find(story.poster_id).full_name}", dashboard_path(User.find(story.poster_id))
  div
    small
      | Posted on: 
      == story.created_at.strftime("%b %d, %Y")
  div
    small My last comment:
    div
      == Comment.where(story_id: story, user_id: @user).last.body.truncate(100)

app/views/dashboard/_commented_stories.js.erb
$("#dashboard_partial").html("<%= j render partial: 'commented_stories.html.slim' %>");

app/views/dashboard/_followers.html.slim
h2 List of All Followers:
- @followers.each do |follower|
  div
    == link_to User.find(follower.follower_id).full_name, dashboard_path(follower.follower_id)
    == render partial: 'followings/form', locals: { user: User.find(follower.follower_id), follower: current_user }

app/views/dashboard/_followers.js.erb
$("#dashboard_partial").html("<%= j render partial: 'followers.html.slim' %>");

app/views/dashboard/_followings.html.slim
h2 List of All Followings:
- @followings.each do |following|
  div
    == link_to User.find(following.user_id).full_name, dashboard_path(following.user_id)
    == render partial: 'followings/form', locals: { user: User.find(following.user_id), follower: current_user }

app/views/dashboard/_followings.js.erb
$("#dashboard_partial").html("<%= j render partial: 'followings.html.slim' %>");

app/views/dashboard/_notifications.html.slim
h2 List of All Notifications:
- unless @unread_notifications.empty?
  == link_to "Mark all as read", mark_all_as_read_path(@uuser)
- @notifications.each do |notification|
  div.notification 
    == notification_text(notification)
    div
      == " "+time_ago_in_words(notification.created_at)
      |  ago
    div.unread
      - unless notification.read?
        | UNREAD
        div
          == link_to "Mark as read", mark_as_read_path(notification), remote: true

app/views/dashboard/_notifications.js.erb
$("#dashboard_partial").html("<%= j render partial: 'notifications.html.slim' %>");

app/views/dashboard/_pagetop.html.slim
h1 Welcome to the Dashboard!

div#user_registration
  h4 
    | Name: 
    == @user.full_name
  div
    = user_photo(@user)
  div 
    - if @user.about_me?
      | About Me: 
      == @user.about_me
  - if @user == current_user
    == link_to "Edit", edit_user_dashboard_registration_path(@user), remote: true
  - else
    == render partial: 'followings/form', locals: { user: @user, follower: current_user }
    
div
  - if @user == current_user
    == link_to "Stories: #{@authored_stories.count}", authored_stories_dashboard_path(@user), remote: true
    /|   
    /== link_to "Likes: #{@liked_stories.count}", liked_stories_dashboard_path(@user), remote: true
    |  
    == link_to "Saves: #{@bookmarked_stories.count}", bookmarked_stories_dashboard_path(@user), remote: true
    |  
    == link_to "Comments: #{@commented_stories.count}", commented_stories_dashboard_path(@user), remote: true
  - else
    == link_to "Stories: #{@posted_stories.published.count}", authored_stories_dashboard_path(@user), remote: true
    /|   
    /== link_to "Likes: #{@liked_stories.count}", liked_stories_dashboard_path(@user), remote: true
  |  
  == link_to "Followers: #{@followers.count}", followers_dashboard_path(@user), remote: true
  |  
  == link_to "Following: #{@followings.count}", followings_dashboard_path(@user), remote: true
  |  
  - if @user == current_user
    == link_to "Notifications: #{@unread_notifications.count}", notifications_dashboard_path(@user), remote: true

app/views/dashboard/notifications.html.slim
== render partial: 'dashboard/pagetop'
div#dashboard_partial
  == render partial: 'dashboard/notifications'

app/views/dashboard/show.html.slim
h1 Welcome to the Dashboard!

div#user_registration
  h4 
    | Name: 
    == @user.full_name
  div
    = user_photo(@user)
  div 
    - if @user.about_me?
      | About Me: 
      == @user.about_me
  - if @user == current_user
    == link_to "Edit", edit_user_dashboard_registration_path(@user), remote: true
  - else
    == render partial: 'followings/form', locals: { user: @user, follower: current_user }
    
div
  - if @user == current_user
    == link_to "Stories: #{@authored_stories.count}", authored_stories_dashboard_path(@user), remote: true
    /|   
    /== link_to "Likes: #{@liked_stories.count}", liked_stories_dashboard_path(@user), remote: true
    |  
    == link_to "Saves: #{@bookmarked_stories.count}", bookmarked_stories_dashboard_path(@user), remote: true
    |  
    == link_to "Comments: #{@commented_stories.count}", commented_stories_dashboard_path(@user), remote: true
  - else
    == link_to "Stories: #{@posted_stories.published.count}", authored_stories_dashboard_path(@user), remote: true
    /|   
    /== link_to "Likes: #{@liked_stories.count}", liked_stories_dashboard_path(@user), remote: true
  |  
  == link_to "Followers: #{@followers.count}", followers_dashboard_path(@user), remote: true
  |  
  == link_to "Following: #{@followings.count}", followings_dashboard_path(@user), remote: true
  |  
  == link_to "Notifications: #{@unread_notifications.count}", notifications_dashboard_path(@user), remote: true
 

div#dashboard_partial
  == render partial: 'authored_stories'