config/routes.rb
Rails.application.routes.draw do

  devise_for :models
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  
  root to: 'stories#index'
  
  resources :stories do 
    resources :comments
    resources :bookmarks
    resources :pictures, only: [:destroy, :new, :create]
  end
  
  namespace :admin do
    root to: 'stories#index'
    resources :stories
  end
  
  resources :dashboard, except: [:index] do
    member do
      get 'authored_stories'
      get 'bookmarked_stories'
      get 'commented_stories'
      get 'followers'
      get 'followings'
      get 'notifications'
    end
    devise_for :users, controllers: { registrations: 'registrations' }
  end
  
  resources :reactions, only: [:create, :destroy]
  
  resources :followings, only: [:show, :create, :destroy]
  
  resources :registration_steps, only: [:show, :update]

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :story
  belongs_to :user
  
  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_story
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :redirect_cancel, :only => [:update]
  
  def index
    @comment = @story.comments.all
  end
  
  def create
    unless current_user
      flash[:warning] = "Please sign in to continue"
      redirect_to new_user_session_path
    else
      @comment = @story.comments.build(comment_params)
      @comment.user = current_user    
      respond_to do |format|
        if @comment.save
          create_notification(@comment)
          flash[:success] = "Comment has been added"
          format.html { redirect_to story_path(@story) }
        else
          flash.now[:warning] = "Comment has not been added"
          format.js {render :partial => 'comments/commenterrors', :data => @comment.to_json }
        end
      end
    end
  end
  
  def edit
    if @comment.user != current_user
      flash[:alert] = "You can only edit your own comments"
      redirect_to story_path(@story)
    end   
    respond_to do |format|
      format.js
    end
  end
  
  def update
    if @comment.user != current_user
      flash[:alert] = "You can only edit your own comments"
      redirect_to story_path(@story)
    else
      respond_to do |format|
        if @comment.update(comment_params)
          flash[:success] = "Comment has been updated"
          format.html {redirect_to story_path(@story)}
        else
          flash.now[:warning] = "Comment has not been updated"
          format.js {render :partial => 'comments/commenterrors', :data => @comment.to_json }
        end
      end
    end
  end
  
  def destroy
    if @comment.user != current_user
      flash[:alert] = "You can only edit your own comments"
      redirect_to story_path(@story)
    else
      if @comment.destroy
        destroy_notification(@comment)
        flash[:success] = "Comment has been deleted"
        redirect_to story_path(@story)
      end
    end
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:body)
  end
  
  def set_story
    @story = Story.find(params[:story_id])#if just :id, it's comment id
  end
    
  def set_comment
    @comment = @story.comments.find(params[:id])
  end
  
  def redirect_cancel
    redirect_to story_path(@story) if params[:cancel]
  end
  
  def create_notification(comment)
    story = Story.find(comment.story_id)
    unless current_user.id == story.author_id
      #story author gets notification
      Notification.create(user_id: User.find(story.author_id).id,
                          notified_by_user_id: current_user.id,
                          notification_category_id: 2,
                          read: false,
                          origin_id: comment.id)
    end
    #get array of id's of other users who commented
    user_array = []
    Story.find(comment.story_id).comments.each do |existingcomment|
      unless comment.user_id == story.author_id || comment.user_id == existingcomment.user_id || existingcomment.user_id == story.author_id
        user_array.push(existingcomment.user_id)
      end
    end
    user_array.uniq
    user_array.each do |existingcomment_userid|
      #others who commented get a notification
      Notification.create(user_id: User.find(existingcomment_userid).id,
                        notified_by_user_id: current_user.id,
                        notification_category_id: 2,
                        read: false,
                        origin_id: comment.id,
                        options: "commenters")
    end
  end
  
  def destroy_notification(comment)
    unless Notification.where(notification_category_id: 2,
                       origin_id: comment.id).empty?
      Notification.where(notification_category_id: 2,
                       origin_id: comment.id).each(&:destroy)
    end
  end
end

app/views/comments/_commenterrors.js.erb
<% action_array = ["new_comment", "edit_comment_#{@comment[:id]}"] %>
<% if controller.action_name == "create" %>
  <% array_index = 0 %>
<% elsif controller.action_name == "update" %>
  <% array_index = 1 %>
<% end %>  


<% if @comment.errors.any? %>
  $("#flash_notice").html('<div class="callout alert" data-closable><button class="close-button" aria-label="Dismiss alert" type="button" data-close><span aria-hidden="true">&times;</span></button><p><i class="fi-alert"></i> <%= j flash[:warning] %></p></div>');
  <% field_array = ["body"] %>  
  <% for i in 0..@comment.errors.full_messages.length-1 %>
    <% field_array.each do |field| %>
      <% if @comment.errors.full_messages[i].downcase.include? field %>
        $("#<%= j action_array[array_index].to_s %>").each(function() {
  
  
          $(this).find('label[for="comment_<%= j field%>"]').addClass("is-invalid-label");
          $(this).find('#comment_<%= j field%>').addClass("is-invalid-input");
          $(this).find('#comment_<%= j field%>').closest('div').find('span.form-error').addClass("is-visible").html('<p><%= @comment.errors.full_messages[i] %></p>');
        });
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/comments/_form.html.slim
== form_for [@story, @comment], :html => {class: "form"}, remote: true do |f|
  div
    - if controller.action_name == "new" or  controller.action_name == "show"
      = f.label :body, 'New Comment'
    - else controller.action_name == "edit"
      = f.label :body, 'Edit Comment'
    = f.text_area :body, autofocus: true, rows: 10, class: "form-control"
    span class="form-error"
  div
    - if controller.action_name == "new" or controller.action_name == "show"
      = f.submit "Add Comment", class: "button"
    - else controller.action_name == "edit"
      = f.submit class: "button"
      = button_tag t('buttons.cancel'), type: "submit", name: "cancel", value: true

app/views/comments/_show.html.slim
h2 Comments
- persisted_comments = @story.comments.reject { |comment| comment.new_record? }
- if persisted_comments.any?
  - persisted_comments.each do |comment|
    div id="comment_#{comment.id}"
      div
        == comment.body
      div
        == time_ago_in_words(comment.created_at)
        |  ago by 
        == link_to "#{comment.user.full_name}", dashboard_path(comment.user)
      div 
        - if current_user == comment.user
          == link_to "Edit", edit_story_comment_path(@story, comment), remote: true
          == link_to "Delete", story_comment_path(@story, comment), method: :delete, data: {confirm: "Are you sure you want to delete the comment?"}, class: "btn"
- else
  | There are no comments to show.

app/views/comments/edit.html.slim
h3 Editing a Comment
== render 'form'

app/views/comments/edit.js.erb
$("#comment_<%= j @comment[:id].to_s %>").html("<%= j render(:partial => 'form')%>");

app/views/comments/new.html.slim
== render 'form'

app/views/comments/update.js.erb
<% if @comment.errors.any? %>
  $("#flash_notice").html('<div class="callout alert" data-closable><button class="close-button" aria-label="Dismiss alert" type="button" data-close><span aria-hidden="true">&times;</span></button><p><i class="fi-alert"></i> <%= j flash[:alert] %></p></div>');
  <% field_array = ["body"] %>  
  <% for i in 0..@comment.errors.full_messages.length-1 %>
    <% field_array.each do |field| %>
      <% if @comment.errors.full_messages[i].downcase.include? field %>
        $('#edit_comment_<%= j @comment[:id].to_s %>').each(function() { 
          $(this).find('label[for="comment_<%= j field%>"]').addClass("is-invalid-label");
          $(this).find('#comment_<%= j field%>').addClass("is-invalid-input");
          $(this).find('#comment_<%= j field%>').closest('div').find('span.form-error').addClass("is-visible").html('<p><%= @comment.errors.full_messages[i] %></p>');
        });
      <% end %>
    <% end %>
  <% end %>
<% end %>