config/routes.rb
Rails.application.routes.draw do

  devise_for :models
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  
  root to: 'stories#index'
  
  resources :stories do 
    resources :comments
    resources :bookmarks
    resources :pictures, only: [:destroy, :new, :create]
  end
  
  namespace :admin do
    root to: 'stories#index'
    resources :stories
  end
  
  resources :dashboard, except: [:index] do
    member do
      get 'authored_stories'
      get 'bookmarked_stories'
      get 'commented_stories'
      get 'followers'
      get 'followings'
      get 'notifications'
    end
    devise_for :users, controllers: { registrations: 'registrations' }
  end
  
  resources :reactions, only: [:create, :destroy]
  
  resources :followings, only: [:show, :create, :destroy]
  
  resources :registration_steps, only: [:show, :update]

end

app/views/shared/_footer.html.slim
footer role="contentinfo" class="footer"
  div[class="row full-width" data-equalizer data-equalize-on='medium']
    div class="small-12 medium-3 large-4 columns"
      h4[data-equalizer-watch] Test
      //i class="fi-laptop"
    div class="small-12 medium-3 large-4 columns"
      //i class="fi-html5"
      h4[data-equalizer-watch] Test
    div class="small-6 medium-3 large-2 columns"
      div[data-equalizer-watch]
        h4 Lorem Imsup
        ul class="footer-links"
          li
            a href="#" Link1
          li
            a href="#" Link2
    div class="small-6 medium-3 large-2 columns"
      div[data-equalizer-watch]
        h4 Follow Us
        ul class="footer-links"
          li
            a href="#" Facebook
          li
            a href="#" Twitter
  div class="row full-width"
    small Copyright &copy; GiftOn 2016

app/views/shared/_header.html.slim
header role="banner"
  nav
    div
      == link_to "Home", root_path
    div
      - if user_signed_in?
        - unless current_page? registration_step_path(:basic_details)
          div
            == link_to "My Dashboard", dashboard_path(current_user)
          div
            == link_to "Sign out", destroy_user_session_path, method: :delete
          div class="navbar-right"
            == signed_in_user
      - else
        == link_to "Sign up", new_user_registration_path
        == link_to "Sign in", new_user_session_path

app/views/shared/_main.html.slim
div#flash_notice
  - flash.each do |name, msg|
    - if name == "notice" && msg != nil
      div[class="callout primary" data-closable]
        == content_tag :div, msg if msg.is_a?(String)
        button[class="close-button" aria-label="dismiss alert" type="button" data-close]
          span[aria-hidden="true"] &times;
    - elsif msg == nil
    - else
      div[class="callout #{name}" data-closable]
        == content_tag :div, msg if msg.is_a?(String)
        button[class="close-button" aria-label="dismiss alert" type="button" data-close]
          span[aria-hidden="true"] &times;
      
== yield