config/routes.rb
Rails.application.routes.draw do

  devise_for :models
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  
  root to: 'stories#index'
  
  resources :stories do 
    resources :comments
    resources :bookmarks
    resources :pictures, only: [:destroy, :new, :create]
  end
  
  namespace :admin do
    root to: 'stories#index'
    resources :stories
  end
  
  resources :dashboard, except: [:index] do
    member do
      get 'authored_stories'
      get 'bookmarked_stories'
      get 'commented_stories'
      get 'followers'
      get 'followings'
      get 'notifications'
    end
    devise_for :users, controllers: { registrations: 'registrations' }
  end
  
  resources :reactions, only: [:create, :destroy]
  
  resources :followings, only: [:show, :create, :destroy]
  
  resources :registration_steps, only: [:show, :update]

end

app/models/story.rb
class Story < ApplicationRecord
  validates :raw_title, presence: true
  validates :raw_body, presence: true
  
  attr_accessor :validate_final_fields
  attr_accessor :validate_updated_fields
  attr_accessor :validate_main_image
  def validate_final_fields?
    validate_final_fields == 'true' || validate_final_fields == true
  end
  def validate_updated_fields?
    validate_updated_fields == 'true' || validate_updated_fields == true
  end
  def validate_main_image?
    validate_main_image == 'true' || validate_main_image == true
  end
  validates :final_title, presence: true, if: :validate_final_fields?
  validates :final_body, presence: true, if: :validate_final_fields?
  validates :updated_title, presence: true, if: :validate_updated_fields?
  validates :updated_body, presence: true, if: :validate_updated_fields?
  
  belongs_to :user
  
  has_many :comments, dependent: :destroy  # If story gets deleted, the depending comment also gets deleted
  has_many :bookmarks, dependent: :destroy
  has_many :pictures, dependent: :destroy
  has_many :reactions, dependent: :destroy
  has_many :reaction_categories, through: :reactions

  accepts_nested_attributes_for :pictures, limit: 15, reject_if: :all_blank
  validates_associated :pictures
  
  has_attached_file :main_image, styles: {
    medium: '300x300>', 
    large: '1000x1000>' 
  }
  
  validates_attachment :main_image, :content_type => { content_type: ["image/jpeg", "image/jpg", "image/gif", "image/png"] }, :size => { in: 0..8.megabytes }, :presence => true, if: :validate_main_image?
  
  default_scope { order(created_at: :desc)}
  scope :published, -> { where(published: true) }
  scope :unpublished, -> { where(published: false) }
end

app/controllers/admin/stories_controller.rb
class Admin::StoriesController < ApplicationController
#  before_action :authenticate_user!, except: [:index, :show]
  before_action :require_admin
  before_action :set_story, only: [:show, :edit, :update, :destroy]
  
  def index
    @stories = Story.unpublished
  end
  
  def show
  end
  
  def edit
  end
  
  def destroy
    if @story.destroy
      destroy_notification(@story)
      flash[:success] = "Story has been deleted"
      redirect_to admin_stories_path
    end
  end
  
  def update
    @story.validate_final_fields = true
    @story.validate_main_image = true
    @story.admin_id = current_user[:id]
    unless @story.published? 
      @story.published = true
      @story.admin_published_at = DateTime.current
    end
    unless @story.anonymous?
      @story.poster_id = @story.author_id
    else
      @story.poster_id = 3
    end
    @story.last_user_to_update = "Admin"
    respond_to do |format|
      if @story.update(story_params)
        create_notification(@story)
        flash[:success] = "Story has been updated"
        format.html {redirect_to admin_story_path(@story)}
      else
        flash.now[:alert] = "Story has not been updated"
        format.html {render :edit}
        format.js {render :partial => 'admin/stories/storyerrors', :data => @story.to_json }
      end
    end
  end
  
  private
  def story_params
    params.require(:story).permit(:final_title, :final_body, :published, :admin_published_at, :main_image)
  end
  
  def require_admin
    unless current_user.admin?
      redirect_to root_path
      flash[:alert] = "Error."
    end
  end
  
  def set_story
    @story = Story.find(params[:id])
  end
  
  def create_notification(story)
    #Notification to story author
    Notification.create(user_id: story.author_id,
                        notified_by_user_id: current_user.id,
                        notification_category_id: 1,
                        read: false,
                        origin_id: story.id)
    #Notification for all people who follow the poster
    followings = Following.where(user_id: story.poster_id)
    followings.each do |follower|
      Notification.create(user_id: follower.follower_id,
                        notified_by_user_id: current_user.id,
                        notification_category_id: 1,
                        read: false,
                        origin_id: story.id,
                        options: "followers")
    end
  end
  def destroy_notification(story)
    unless Notification.where(notification_category_id: 1,
                       origin_id: story.id).empty?
      Notification.where(notification_category_id: 1,
                       origin_id: story.id).each(&:destroy)
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_story, only: [:show, :edit, :update, :destroy, :check_for_cancel]
  before_action :redirect_cancel, :only => [:update]
  
  def index
    @stories = Story.published
  end
  
  def new
    @story = Story.new
    @story.pictures.build(:image => params[:image])   
  end
  
  def create
    @story = current_user.stories.build(story_params)
    @story.published = false
    @story.author_id = current_user[:id]
    respond_to do |format|
      if params[:image]
        params[:image].each { |image|
          @picture = @story.pictures.build(image: image)
        }
      end
      if @picture.nil? || !@picture.errors.any?
        if @story.save
          flash[:success] = "Story has been submitted"
          format.html {redirect_to dashboard_path(current_user)}
        end
      end
      unless @story.save
        flash.now[:alert] = "Story has not been submitted"
        format.html {render :new}
        format.js {render :partial => 'stories/storyerrors', :data => [ @story.to_json, @picture.to_json ] }
      end
    end
  end
  
  def show
    @comment = @story.comments.build
    @bookmark = @story.bookmarks.build
  end
  
  def edit
    if @story.user != current_user
      flash[:warning] = "You can only edit your own stories."
      redirect_to root_path
    end
  end
  
  def update
    if @story.published?
      @story.validate_updated_fields = true
    else
      if @story.anonymous?
        @story.poster_id = nil
      end
    end
    @story.last_user_to_update = "Author"
    respond_to do |format|
      if @story.user != current_user
        flash[:warning] = "You can only edit your own stories."
        redirect_to root_path
      else
        if @story.update(story_params)
          flash[:success] = "Story has been updated"
          format.html {redirect_to dashboard_path(current_user)}
        else
          flash.now[:alert] = "Story has not been updated"
          format.html {render :edit} #renders edit tmplt again
          format.js {render :partial => 'stories/storyerrors', :data => @story.to_json }
        end
      end
    end
  end
  
  def destroy
    if @story.destroy
      flash[:success] = "Story has been deleted"
      redirect_to stories_path
    end
  end
  
  private
  
  def story_params
    params.require(:story).permit(:raw_title, :raw_body, :updated_title, :updated_body, :anonymous, :review, pictures_attributes: [:id, :story_id, :_destroy, :image])
  end
  
  def set_story
    @story = Story.find(params[:id])
    #to make sure users can only get to their own stories
    #@story = current_user.stories.find(params[:id]) #This first grabs the user, then grabs their stories, starts with a smaller scope than all stories
  end
  
  def redirect_cancel
    redirect_to story_path(@story) if params[:cancel]
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
  def story_main_image_show(story)
    unless story.main_image_file_name.nil?
      image_tag story.main_image.url
    end
  end
  
  def story_title_show(story)
    if story.published?
      if story.last_user_to_update == "Admin"
        body = story.final_title
      else
        body = story.updated_title
      end
    else
      body = story.raw_title
    end
  end
  
  def story_body_show(story)
    if story.published?
      if story.last_user_to_update == "Admin"
        body = story.final_body
      else
        body = story.updated_body
      end
    else
      body = story.raw_body
    end
    html = "<div>#{body}</div>".html_safe
  end
  
  def story_by_show(story)
    if story.published?
      link = link_to "#{User.find(story.poster_id).full_name}", dashboard_path(User.find(story.poster_id))
      partial =  render partial: 'followings/form', locals: { user: User.find(story.poster_id), follower: current_user }
      html = "<div>Posted by: #{link}</div><div>#{partial}</div>".html_safe
     
    else
      if story.anonymous?
        html = "<div>Posted by: Anonymous</div>"
      else
        link = link_to "#{User.find(story.author_id).full_name}", dashboard_path(User.find(story.author_id))
        html = "<div>Posted by: #{link}".html_safe
      end
    end
  end
  
  def truncate_body_list(body)
    body.gsub!('<br>', ' ')
    body.gsub!('</li>', ' ')
    body.gsub!('<ol>', ' ')
    body.gsub!('<ul>', ' ')
    truncate(strip_tags("#{body}").gsub('&amp;','&'), length: 150)
  end
end

app/views/stories/_form.html.slim
- if (controller.action_name == "new") || (controller.action_name == "edit" && !@story.final_title )
  = form_for(@story, :html => {class: "form", multipart: true}, remote: true) do |f|
    - if (controller.action_name == "new")
      div#picture_fields
        = f.fields_for :pictures do |picture|
          = picture.label :image
          = picture.file_field :image, multiple: true, :name =>"image[]"
          /OTHERWISE, the name would be: /story[pictures_attributes][0][image][]
        .links
          = link_to_add_association 'Add another image', f, :pictures
        span class="form-error"
    div
      = f.label :raw_title, "Title"
      = f.text_field :raw_title, autofocus: true, value: @story.raw_title
      span class="form-error"
    div
      = f.label :raw_body, "Body"
      = f.trix_editor :raw_body
      span class="form-error"
    div
      = f.label :anonymous
      = f.check_box :anonymous, type: "checkbox"
    div
      = f.radio_button :review, false
      = f.label :review, "No, thanks"
      = f.radio_button :review, true
      = f.label :review, "Yes, thanks a lot!"
    div
      - sanitize @story.raw_body
      = f.submit "Contribute Story", class: "button"
- elsif controller.action_name == "edit"
  = form_for(@story, :html => {class: "form"}, remote: true) do |f|
    div
      = f.label :updated_title, "Title"
      = f.text_field :updated_title, autofocus: true, value: (@story.last_user_to_update == "Admin") ? @story.final_title : @story.updated_title
      span class="form-error"
    div
      = f.label :updated_body, "Body"
      == f.trix_editor :updated_body
      span class="form-error"
    div
      = f.label :anonymous
      = f.check_box :anonymous, type: "checkbox"
    div
      - unless @story.final_title?
        = f.radio_button :review, false
        = f.label :review, "No, thanks", checked: true
        = f.radio_button :review, true
        = f.label :review, "Yes, thanks a lot!"
    div
      - sanitize @story.updated_body
      = f.submit class: "button"
      = button_tag t('buttons.cancel'), type: "submit", name: "cancel", value: true
script
  == render partial: 'trix_input_id.js.erb', story: @story

app/views/stories/_picture_fields.html.slim
.nested-fields
  = f.file_field :image, multiple: true, :name =>"image[]"
  = link_to_remove_association "Remove Image", f

app/views/stories/_storyerrors.js.erb
<% action_array = ["new_story", "edit_story_#{@story[:id]}"] %>
<% if controller.action_name == "create" %>
  <% array_index = 0 %>
<% elsif controller.action_name == "update" %>
  <% array_index = 1 %>
<% end %>  

$("#<%= j action_array[array_index].to_s %> label.is-invalid-label").removeClass("is-invalid-label");
$("#<%= j action_array[array_index].to_s %> input.is-invalid-input, #<%= j action_array[array_index].to_s %> textarea.is-invalid-input").removeClass("is-invalid-input");
$('trix-editor.formatted_content').removeClass("is-invalid-input");
$("#<%= j action_array[array_index].to_s %> span.form-error").remove("p");
$("#<%= j action_array[array_index].to_s %> span.form-error.is-visible").removeClass("is-visible");
;

<% unless @picture.nil? %>
  <% if @picture.errors.any? %>
    $("#flash_notice").html('<div class="callout alert" data-closable><button class="close-button" aria-label="Dismiss alert" type="button" data-close><span aria-hidden="true">&times;</span></button><p><i class="fi-alert"></i> <%= j flash[:alert] %></p></div>');

    $('label[for="picture_image"]').addClass("is-invalid-label");
    $('#picture_image').addClass("is-invalid-input");
    $('#picture_fields span.form-error').addClass("is-visible").html("<p><%= @picture.errors.full_messages.first %></p>");
  <% end %>
<% end %>

<% if @story.errors.any? %>
  $("#flash_notice").html('<div class="callout alert" data-closable><button class="close-button" aria-label="Dismiss alert" type="button" data-close><span aria-hidden="true">&times;</span></button><p><i class="fi-alert"></i> <%= j flash[:alert] %></p></div>');

  <% field_array = ["title", "body"] %> 
  <% if array_index == 0 %>
    <% for i in 0..@story.errors.full_messages.length-1 %>
      <% field_array.each do |field| %>
        <% if @story.errors.full_messages[i].downcase.include? field %>
          $('label[for="story_<%= j "raw_"+field%>"]').addClass("is-invalid-label");
          $('#story_<%= j "raw_"+field%>').addClass("is-invalid-input");
          <% if field == "body" %>
            $('trix-editor.formatted_content').addClass("is-invalid-input");
            $('trix-editor.formatted_content').closest('div').find('span.form-error').addClass("is-visible").html("<p><%= @story.errors.full_messages[i].gsub!(/.*?(?<=Raw ).*?/im, "").capitalize %></p>");
          <% end %>
          $('#story_<%= j "raw_"+field%>').closest('div').find('span.form-error').addClass("is-visible").html("<p><%= @story.errors.full_messages[i].gsub!(/.*?(?<=Raw ).*?/im, "").capitalize %></p>");
        <% end %>
      <% end %>
    <% end %>
  
  <% else %>
    <% for i in 0..@story.errors.full_messages.length-1 %>
      <% field_array.each do |field| %>
        <% if @story.errors.full_messages[i].downcase.include? field %>
          $('label[for="story_<%= j "updated_"+field%>"]').addClass("is-invalid-label");
          $('#story_<%= j "updated_"+field%>').addClass("is-invalid-input");
          <% if field == "body" %>
            $('trix-editor.formatted_content').addClass("is-invalid-input");
            $('trix-editor.formatted_content').closest('div').find('span.form-error').addClass("is-visible").html("<p><%= @story.errors.full_messages[i].gsub!(/.*?(?<=Updated ).*?/im, "").capitalize %></p>");
          <% end %>
          $('#story_<%= j "updated_"+field%>').closest('div').find('span.form-error').addClass("is-visible").html("<p><%= @story.errors.full_messages[i].gsub!(/.*?(?<=Updated ).*?/im, "").capitalize %></p>");
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/stories/_trix_input_id.js.erb
function htmlDecode(input){
  var e = document.createElement('div');
  e.innerHTML = input;
  return e.childNodes[0].nodeValue;
}

function toJSDate(dateTime) {
  var dateTime = dateTime.split(" ");
  var date = dateTime[0].split("-");
  var time = dateTime[1].split(":");
  
  //(year, month, day, hours, minutes, seconds, milliseconds)
  //subtract 1 from month because Jan is 0 and Dec is 11
  return new Date(date[2], (date[1]-1), date[0], time[0], time[1], 0, 0);
}

$(document).ready(function() {

  if ("<%= @story.last_user_to_update %>" == "Admin") {
    $("input#story_updated_body_trix_input_story_<%= j @story.id.to_s %>").attr('value', htmlDecode("<%= @story.final_body %>"));     
  } else {
    $("input#story_updated_body_trix_input_story_<%= j @story.id.to_s %>").attr('value', htmlDecode("<%= @story.updated_body %>"));    
  };
});

app/views/stories/edit.html.slim
h3 Editing a Story
== render 'form'

app/views/stories/index.html.slim
h1 List of all Stories
- if user_signed_in?
  == link_to "New Story", new_story_path, class: "btn", id: "new-story-btn"

- @stories.each do |story|
  div 
    == story_main_image_show(story)
  div
    == link_to story_title(story), story_path(story)
  div
    == story_body(story)
  div
    - if story.poster_id?
      small 
        | Posted by: 
        == link_to "#{User.find(story.poster_id).full_name}", dashboard_path(User.find(story.poster_id))

app/views/stories/new.html.slim
h3 Add New Story
div#error_block
== render 'form'

app/views/stories/show.html.slim
div 
  == story_main_image_show(@story)
h2
  == story_title_show(@story)
div
  == story_by_show(@story)
p.small
  == @story.created_at.strftime("%b %d, %Y")
p
  == story_body_show(@story)
- if user_signed_in? && current_user == @story.user(:author_id)
  == link_to "Edit Story", edit_story_path(@story), class: "btn"
  == link_to "Delete Story", story_path(@story), method: :delete, data: {confirm: "Are you sure you want to delete the story?"}, class: "btn"
div.story_pictures
  - unless @story.pictures.empty?
    - @story.pictures.each do |picture|
      = image_tag picture.image.url
      - if user_signed_in? && current_user == @story.user(:author_id)
        = link_to "Delete Picture", story_picture_path(@story, picture), data: {confirm: "Are you sure?"}, method: :delete
  - if user_signed_in? && current_user == @story.user(:author_id)
    div
      = link_to "Upload More Pictures", new_story_picture_path(@story), class: "btn"

- if @story.published?
  <!--  Code for adding and displaying comments follows. Note: This is on the story show view -->
  == render 'comments/form'
  == render 'comments/show'

  <!-- Bookmarks -->
  == render 'bookmarks/show'
  
  <!-- Reactions -->
  == render 'reactions/show'